# Site settings
title: Sam Parsons
tagline: software engineering leader
email: sjparsons@gmail.com
description: "I'm a software engineering leader who is passionate about building web services and creating effective teams."
baseurl: ""
url: "http://sjparsons.com"

permalink: "/:year/:month/:day/:title"

markdown: kramdown

exclude:
  - README.md
  - css/bower_components
  - css/sjparsons.scss
  - css/watch.sh
