# Site settings
title: Sam Parsons
tagline: software engineer and leader
email: sjparsons@gmail.com
description: "I'm a software engineer and leader who is passionate about building web apps with React and GraphQL"
baseurl: ""
url: "http://sjparsons.com" # the base hostname & protocol for your site
twitter: sjparsons

permalink: "/:year/:month/:day/:title"

# Build settings
markdown: kramdown

exclude:
  - deploy.sh
  - README.md
  - css/bower_components
  - css/sjparsons.scss
  - css/watch.sh
